# 写一个docker compose 文件，启动一个postgres 和一个redis
version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432"
  redis:
    container_name: redis
    image: redis:7.2.3-alpine3.18
    ports:
      - "6379"