server:
  port: 8080

spring:
  flyway:
    clean-disabled: true
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    out-of-order: false
    schemas: public

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000
      connect-timeout: 10000

datapoint:
  cache:
    expire-in-millis: 300000

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    root: "warn"
    com.frank.redissondemo: "info"